# Configuration for tuning and/or shared settings across the system
log:
  dir: ./logs
  level: DEBUG
  images: true

gemini:
  location: europe-west1
  model:
    flash:
      name: gemini-1.5-flash-001 # Discontinued on May 24, 2025


fast:
  tile:
    num_frames: 1
    size: [320, 240]
    # Alternate sizes
    # size: (640, 480)
    # size: (1024, 1024)
  model:
    name: claude-3-haiku-20240307
    # Alternate models
    # name: claude-3-opus-20240229
    # name: claude-3-sonnet-20240229
    temperature: 0.0
  system_prompt_file: data/prompts/fast/system_prompt_novelty_stopwords
  novelty_threshold: 20  # Ignore narrations with novelty below this threshold
  memory:
    size: 3  # Number of frames to keep in memory (excludes current frame)
    max_images: 1000 # Maximum number of images to keep in memory (becomes only descriptions otherwise)
    novelty_threshold: 20  # If negative, retain all frames in memory regardless of novelty


slow:
  embed:
    batch_size: 1
    model:
      name: BAAI/bge-m3

  reddit:
    vet_prompt: data/prompts/slow/vet.prompt
    hf_repo_id: mvsoom/gedankenpolizei
    hf_slow_thoughts_file: slow_thoughts.feather

  bias:
    # The `beta` parameter controls the amount of bias in the walk in SLOW space in terms of *relative* gain
    # Proposal steps in SLOW space are projected onto the hyperplane specified by the `bias_directions`, such that their direction but NOT their length is changed. There are three regimes:
    # 1. For `beta` -> -infty, all bias is removed from the step
    # 2. For `beta` ~= 0, bias is amplified according to approx (1 + beta). For example, `beta` = 0.1 amplifies the bias by 10%, `beta` = -0.1 reduces the bias by 10%. `beta` = 0 disables biasing.
    # 3. For `beta` -> infty, the step direction is completely aligned with the bias direction
    # (generally a very small effect unless there are 100s of directions)
    beta: -.inf

    # The `strength` parameter in [0, 1] controls the amount of bias in the walk in SLOW space
    # A value of 0. means no bias is applied to the step
    # A value of 1. means that the projections of the step onto the bias directions are enforced to be at least unity, even if they were negative originally
    strength: 0.

    # Bias directions are relative vectors in SLOW space that are used to bias the direction of the walk in SLOW space
    # They are computed as `bias_direction = overall_multiplier*multiplier*(embed(to) - embed(from))`
    # Note: the `*multiplier` parameters can be negative
    # Note: embeddings are usually normalized to have unit norm, so the `*multipliers` can be used to dominate the step size
    directions:
      - from: "neutral"
        to: "happy"
        multiplier: 1.0
      - from: "angry"
        to: "giggly"
        multiplier: 1.0
    
    overall_multiplier: 1.0  # Overall multiplier for the bias directions


now:
  model:
    name: claude-3-opus-20240229
    temperature: 1.0
  user_prompt_file: data/prompts/now/user_prompt_fixed_width
  terminal_width: 16

