# Configuration for tuning and/or shared settings across the system
log:
  dir: ./logs
  level: DEBUG
  images: true

gemini:
  location: europe-west1
  model:
    flash:
      name: gemini-1.5-flash-001 # Discontinued on May 24, 2025


fast:
  tile:
    num_frames: 1
    size: [320, 240]
    # Alternate sizes
    # size: (640, 480)
    # size: (1024, 1024)
  model:
    name: claude-3-haiku-20240307
    # Alternate models
    # name: claude-3-opus-20240229
    # name: claude-3-sonnet-20240229
    temperature: 0.0
  system_prompt_file: data/prompts/fast/system_prompt_novelty_stopwords
  novelty_threshold: 20  # Ignore narrations with novelty below this threshold
  memory:
    size: 3  # Number of frames to keep in memory (excludes current frame)
    max_images: 1000 # Maximum number of images to keep in memory (becomes only descriptions otherwise)
    novelty_threshold: 20  # If negative, retain all frames in memory regardless of novelty


slow:
  embed:
    model:
      name: BAAI/bge-m3

  reddit:
    vet_prompt: data/prompts/slow/vet.prompt
    hf_repo_id: mvsoom/gedankenpolizei
    hf_slow_thoughts_file: slow_thoughts.feather

  bias:
    # The `intensity` parameter in [0, 1] controls the amount of bias in the walk in SLOW space
    # A value of 0. means no bias is applied to the step
    # A value of 1. means that the projections of the step onto the bias directions are enforced to be at least unity, even if they were negative originally
    intensity: 0.

    # Bias directions are relative vectors in SLOW space that are used to bias the direction of the walk in SLOW space
    # They are computed as `bias_direction = overall_multiplier*multiplier*(embed(to) - embed(from))`
    # Note: the `*multiplier` parameters can be negative
    # Note: embeddings are usually normalized to have unit norm, so the `*multipliers` can be used to dominate the step; a very large `overall_multiplier` will always align the step with the bias direction for any `intensity > 0`
    directions:
      - from: "neutral"
        to: "happy"
        multiplier: 1.0
      - from: "angry"
        to: "giggly"
        multiplier: 1.0
    
    overall_multiplier: 1.0
  
  walk:
    max_steps: 10


now:
  model:
    name: claude-3-opus-20240229
    temperature: 1.0
  user_prompt_file: data/prompts/now/user_prompt_fixed_width
  terminal_width: 16

