#!/bin/bash
# Send stdin text stream to cool-retro-term
PROFILE= # TODO
SIZE=300x990 # Terminal window's width x height

# Create a new named pipe
PIPE=/tmp/retroterm_pipe_$$
[ -e $PIPE ] && rm $PIPE
mkfifo $PIPE

# Set up trap to catch SIGINT, SIGTERM, and SIGCHLD (when the retro term process ends)
cleanup() {
    rm -f $PIPE
    kill $TERM_PID 2>/dev/null
    exit 0
}
trap cleanup SIGINT SIGTERM SIGCHLD

# Launch cool-retro-term and run a command to read from the named pipe
RUNCMD="(clear; tail -f $PIPE | lolcat -a)"
cool-retro-term \
    -geometry ${SIZE}+0+0 \
    --profile "$PROFILE" \
    -e /bin/bash -c "$RUNCMD" > /dev/null 2>&1 &

TERM_PID=$!

# Ensure that the script also exits if the process piping to stdin exits
while IFS= read -r -n1 -s INPUT; do
    echo -n "$INPUT" > $PIPE
done < /dev/stdin

cleanup