import re

REDACTED_KEYWORDS = [
    "redacted",
    "removed",
    "edited",
    "modified",
    "added",
    "removed",
    "updated",
    "fixed",
    "resolved",
    "closed",
    "deleted",
    "censored",
    "hidden",
    "blocked",
    "unavailable",
    "banned",
    "expired",
    "archived",
    "locked",
    "quarantined",
    "private",
    "restricted",
    "suspended",
    "filtered",
    "withheld",
    "concealed",
    "obscured",
    "suppressed",
    "eliminated",
    "erased",
    "expunged",
    "purged",
    "excised",
    "omitted",
    "withdrawn",
    "retracted",
    "unpublished",
    "inaccessible",
]

REDACTED = re.compile(
    r"\[[^\[\]]*(?:" + "|".join(map(re.escape, REDACTED_KEYWORDS)) + r")[^\[\]]*\]",
    re.IGNORECASE,
)
