#!/bin/bash
# Use [sdm](https://github.com/gitbls/sdm) to burn customized RPi image
# Usage: ./burnimg <img> <ssd>

img=$1
ssd=$2

# If ssd is not provided, list options
if [ -z "$ssd" ]; then
    echo "Usage: ./burnimg <img> <ssd>"
    echo "Available SD cards:"
    lsblk -p -o NAME,SIZE,MODEL | grep -E "sd|mmcblk"
    exit 1
fi

args=$(
    # Enable `ssh pi@raspberrypi.local`
    echo "--hostname raspberrypi"
    # Expand the root file system on the SD Card after the burn completes
    echo "--expand-root"
)

# Note: burning takes a long time after "dd Copy completed" due to syncing cached writes
# No problem, just wait 35 minutes

# IT SEEMS LIKE FORMATTING SSD FIRST IS NECESSARY TO HAVE THIS WORK

set -x
# 
echo Please make sure that the burn device is dismounted before starting the burn. The check in sdm for this is broken at the moment, will be fixed in the next release later this month.
# https://github.com/gitbls/sdm/issues/259#issuecomment-2419808373
#sudo sdm $img --burn "$ssd" $args
set +x

# TODO: Unmount the SD card at $ssd